### ISSUE TITLE
Question: Kinetic release

### ISSUE THREAD

**Issue by tdinesh** [ipa320/cob_gazebo_plugins#19]
Is there a plan to release this for Kinetic/Gazebo 7.4?
The hardware_interface::ControllerInfo API is changed. Also Gazebo 7.4  gazebo::physics::Joint API is different.

**Comment by fmessmer** [comment]
We are currently working on preparing kinetic branches for our repos...
However, so far we haven't started to work on this plugin...@ipa-bnm did you have a look at this already?

Contributions are very welcome...I just created a kinetic_dev branch :wink:

**Comment by fmessmer** [comment]
We even might to think about contributing this back to the official https://github.com/ros-controls/gazebo_ros_control package, but there they don't seem to be prepared for kinetic, too....don't know how simulation with gazebo currently works under kinetic at all...I'm not yet there...

**Comment by tdinesh** [comment]
I would be happy to contribute. Had already started to make the API changes. Will create a pull request once I get it working.

**Comment by tdinesh** [comment]
I have the plugin working with kinetic and gazebo. But travis is failing. Can you check the scripts?
travis.install.sh and travis.script.sh.

**Comment by fmessmer** [comment]
Thanks for the PR #21 
However, it might take a while until we are actually able to test and release...

I guess travis fails because it does not support xenial...in all the other repos we are currentliy switching to https://github.com/ros-industrial/industrial_ci which is based on docker.
@ipa-bnm FYI

**Comment by benmaidel** [comment]
+1 for #21
Yes travis is failing because xenial is not officially supported. We switched to `ros-industrial/industrial_ci` but are using our own fork for now. 
@tdinesh An example for an working .travis.yaml for kinetic can be found here: https://github.com/ipa320/cob_environments/tree/kinetic_dev. Would be great if you could include a working travis config into this PR.

**Comment by tdinesh** [comment]
Thanks @ipa-bnm. I have fixed the PR.

**Comment by fmessmer** [comment]
@tdinesh 
Out of couriosity, what (simulated) robot are you using this plugin with?
What's your usecase?
Would you be interested in an E-Stop behavior (see #16)?
Would you support a transfer of the plugin to official [gazebo_ros_pkgs](https://github.com/ros-simulation/gazebo_ros_pkgs) - I already mentioned this once in a [comment](https://github.com/ros-simulation/gazebo_ros_pkgs/issues/179#issuecomment-96958685)?
Just asking because we haven't played back any feature from the original repo...don't know whether there is anything new in gazebo_ros_control plugin anyway

**Comment by tdinesh** [comment]
@ipa-fxm 
We are using the Kuka LBR iiwa 7 platform.
The LBR has SmartServos which can switch torque/position control. But this was not available in Gazebo for https://github.com/SalvoVirga/iiwa_stack.
E-stop behaviour would be good to have. 
I would support a transfer of the plugin. Even, I haven't seen anything new in gazebo_ros_control. 
Hope this answers everything.

**Comment by fmessmer** [comment]
`cob_gazebo_plugins` is release to kinetic (0.7.1-0)
http://repositories.ros.org/status_page/ros_kinetic_default.html?q=cob_gazebo_plugins
