### ISSUE TITLE
Compile error with cob_gazebo_ros_control

### ISSUE THREAD

**Issue by Fan-loewe** [ipa320/cob_gazebo_plugins#46]
Hello,

I am using Ubuntu 18.04 and ROS melodic.
I downloaded the cob_gazebo_ros_control package from branch: kinetic_release_candidate.
When I compile it in my work space with catkin_make, it shows following errors.

![Screenshot from 2020-07-06 23-54-45](https://user-images.githubusercontent.com/44665480/86651773-1a206200-bfe4-11ea-8ed7-a93982c45391.png)

does anyone have the similar problem? Thanks a lot.

**Comment by fmessmer** [comment]
@Fan-loewe
I've just restarted our travis jobs: https://travis-ci.com/github/ipa320/cob_gazebo_plugins/builds/160334464
and they pass for both `kinetic` and `melodic`

`kinetic_release_candidate` should also be the version you get when installing it - `cob_gazebo_ros_control` is released to `melodic` - you can just install it via `sudo apt install ros-melodic-cob-gazebo-ros-control`

other than that, I don't know why you cannot compile it on your machine
do you have any special branch or source overlay for https://github.com/ros-controls/ros_control or https://github.com/ros-simulation/gazebo_ros_pkgs?

**Comment by Fan-loewe** [comment]
@fmessmer 
thank you very much for your quick reply.

Exactly as you said, I have a ros_control package in my working space. After I removed that package,  cob_gazebo_ros_control could be compiled. So it means cob_gazebo_ros_control will get conflict with other controllers?

**Comment by fmessmer** [comment]
what version of ros_control are you using?
can you post the hash/branch here?
it might point us to an upcoming API-break...

**Comment by Fan-loewe** [comment]
@fmessmer 
I suppose the ros_control package is my problem. Before I was using Ubuntu 14.04 Indigo, I downloaded ros_control from the indigo branch, it worked fine at that time.

Since I need a more updated Ubuntu version 18.04 and ros melodic, I copied the packages I used before and make it in the new environment. The ros_control package didn't show any error when I make it but it seems have some potential problems.

I would appreciate it if you can help me with another issue on cob_control_mode_adapter. I downloaded the package from here:
https://github.com/ipa320/cob_control/tree/melodic_release_candidate
when I launch a node including this node, it shows the following error:

![Screenshot from 2020-07-07 16-32-30](https://user-images.githubusercontent.com/44665480/86797212-b0e63080-c06f-11ea-9014-5d52d447f624.png)

but I have this package in my catkin_ws. Do you have any idea what the problem is? Is there anything in the CMakelist I need to change?

**Comment by fmessmer** [comment]
- first, you cannot just copy SW which was working in `indigo` to a `melodic` machine and assume it is still working
likely there have been (API-breaking) changes from during jade, kinetic, lunar, melodic distro
- if you relied on a feature that you implemented for `indigo`, you'll have to migrate/rebase it to the latest version for `melodic`
- if you dont have any custom changes simply try using the released version of the needed packages - no need for source overlays
- you issue with `cob_control_mode_adapter` is not related to `cob_gazebo_plugins` repo
  (likely the package is not in your `CMAKE_PREFIX_PATH` or `ROS_PACKAGE_PATH` - i.e. your workspace is not set up correctly)

closing this issue as it is not a problem with this repo but due to wrong workspace layout of @Fan-loewe

**Comment by Fan-loewe** [comment]
@fmessmer 

thank you very much for your help
